language: java

script: ./gradlew clean build jacocoTestReport

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - openjdk8

after_success:
  - ./gradlew jacocoTestReport coveralls